import type { FormTemplate } from "@/lib/types/form-builder.types"

/**
 * 평가 영역별 기본 템플릿
 * WC: 휠체어 및 이동
 * ADL: 일상생활동작
 * S: 감각
 * SP: 자세
 * EC: 주택 및 환경개조
 * CA: 컴퓨터 접근
 * L: 레저
 * AAC: 보완대체의사소통
 * AM: 자동차 개조
 */

export type AssessmentDomainType = "WC" | "ADL" | "S" | "SP" | "EC" | "CA" | "L" | "AAC" | "AM"

export const assessmentDomainNames: Record<AssessmentDomainType, string> = {
  WC: "휠체어 및 이동",
  ADL: "일상생활동작",
  S: "감각",
  SP: "자세",
  EC: "주택 및 환경개조",
  CA: "컴퓨터 접근",
  L: "레저",
  AAC: "보완대체의사소통",
  AM: "자동차 개조",
}

/**
 * 휠체어 및 이동 평가 템플릿 (WC)
 */
export const wheelchairAssessmentTemplate: FormTemplate = {
  id: "assessment-wc-template",
  name: "휠체어 및 이동 평가",
  description: "휠체어 및 이동 보조기기 평가 양식",
  version: "1.0.0",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  isDefault: true,
  sections: [
    {
      id: "section-basic-info",
      title: "기본 정보",
      order: 0,
      fields: [
        {
          id: "field-evaluation-date",
          type: "date",
          label: "평가일",
          name: "evaluation_date",
          required: true,
          defaultValue: new Date().toISOString().split("T")[0],
          width: "half",
        },
        {
          id: "field-evaluator",
          type: "text",
          label: "평가자",
          name: "evaluator_name",
          width: "half",
        },
      ],
    },
    {
      id: "section-body-measurements",
      title: "신체 치수 측정",
      description: "휠체어 선택을 위한 신체 치수",
      order: 1,
      fields: [
        {
          id: "field-shoulder-width",
          type: "number",
          label: "어깨 너비 (cm)",
          name: "shoulder_width",
          min: 0,
          max: 200,
          step: 0.1,
          width: "third",
        },
        {
          id: "field-hip-width",
          type: "number",
          label: "엉덩이 너비 (cm)",
          name: "hip_width",
          min: 0,
          max: 200,
          step: 0.1,
          width: "third",
        },
        {
          id: "field-seat-depth",
          type: "number",
          label: "좌석 깊이 (cm)",
          name: "seat_depth",
          min: 0,
          max: 200,
          step: 0.1,
          width: "third",
        },
        {
          id: "field-seat-height",
          type: "number",
          label: "좌석 높이 (cm)",
          name: "seat_height",
          min: 0,
          max: 200,
          step: 0.1,
          width: "third",
        },
        {
          id: "field-back-height",
          type: "number",
          label: "등받이 높이 (cm)",
          name: "back_height",
          min: 0,
          max: 200,
          step: 0.1,
          width: "third",
        },
        {
          id: "field-leg-length",
          type: "number",
          label: "다리 길이 (cm)",
          name: "leg_length",
          min: 0,
          max: 200,
          step: 0.1,
          width: "third",
        },
      ],
    },
    {
      id: "section-mobility-assessment",
      title: "이동 능력 평가",
      order: 2,
      fields: [
        {
          id: "field-indoor-mobility",
          type: "select",
          label: "실내 이동 능력",
          name: "indoor_mobility",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-outdoor-mobility",
          type: "select",
          label: "실외 이동 능력",
          name: "outdoor_mobility",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-transfer-ability",
          type: "select",
          label: "이동 능력",
          name: "transfer_ability",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-wheelchair-experience",
          type: "select",
          label: "휠체어 사용 경험",
          name: "wheelchair_experience",
          width: "half",
          options: [
            { label: "신규", value: "new" },
            { label: "1년 미만", value: "less_than_1year" },
            { label: "1-5년", value: "1_to_5years" },
            { label: "5년 이상", value: "more_than_5years" },
          ],
        },
      ],
    },
    {
      id: "section-environment",
      title: "환경 정보",
      order: 3,
      fields: [
        {
          id: "field-living-environment",
          type: "select",
          label: "주거 환경",
          name: "living_environment",
          width: "half",
          options: [
            { label: "단독주택", value: "house" },
            { label: "아파트", value: "apartment" },
            { label: "시설", value: "facility" },
            { label: "기타", value: "other" },
          ],
        },
        {
          id: "field-barriers",
          type: "multiselect",
          label: "환경 장애물",
          name: "barriers",
          width: "full",
          options: [
            { label: "계단", value: "stairs" },
            { label: "문턱", value: "threshold" },
            { label: "좁은 통로", value: "narrow_passage" },
            { label: "경사로", value: "ramp" },
            { label: "기타", value: "other" },
          ],
        },
      ],
    },
    {
      id: "section-evaluation",
      title: "평가 결과",
      order: 4,
      fields: [
        {
          id: "field-evaluator-opinion",
          type: "textarea",
          label: "평가자의견",
          name: "evaluator_opinion",
          rows: 6,
          width: "full",
          placeholder: "평가자의 종합 의견을 입력하세요",
        },
        {
          id: "field-recommended-device",
          type: "textarea",
          label: "추천 보조기기",
          name: "recommended_device",
          rows: 4,
          width: "full",
          placeholder: "추천하는 보조기기 및 사양을 입력하세요",
        },
        {
          id: "field-future-plan",
          type: "textarea",
          label: "향후 계획",
          name: "future_plan",
          rows: 4,
          width: "full",
          placeholder: "향후 계획 및 추천 사항을 입력하세요",
        },
      ],
    },
  ],
}

/**
 * 일상생활동작 평가 템플릿 (ADL)
 */
export const adlAssessmentTemplate: FormTemplate = {
  id: "assessment-adl-template",
  name: "일상생활동작 평가",
  description: "일상생활동작(ADL) 평가 양식",
  version: "1.0.0",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  isDefault: true,
  sections: [
    {
      id: "section-basic-info",
      title: "기본 정보",
      order: 0,
      fields: [
        {
          id: "field-evaluation-date",
          type: "date",
          label: "평가일",
          name: "evaluation_date",
          required: true,
          defaultValue: new Date().toISOString().split("T")[0],
          width: "half",
        },
        {
          id: "field-evaluator",
          type: "text",
          label: "평가자",
          name: "evaluator_name",
          width: "half",
        },
      ],
    },
    {
      id: "section-adl-activities",
      title: "일상생활동작 평가",
      description: "각 활동별 독립도 평가",
      order: 1,
      fields: [
        {
          id: "field-eating",
          type: "select",
          label: "식사",
          name: "eating",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-dressing",
          type: "select",
          label: "착의",
          name: "dressing",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-grooming",
          type: "select",
          label: "세면/목욕",
          name: "grooming",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-toileting",
          type: "select",
          label: "배뇨/배변",
          name: "toileting",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-transfer",
          type: "select",
          label: "이동",
          name: "transfer",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
        {
          id: "field-mobility",
          type: "select",
          label: "보행",
          name: "mobility",
          width: "half",
          options: [
            { label: "독립", value: "independent" },
            { label: "최소 보조", value: "minimal_assist" },
            { label: "보조 필요", value: "assist_required" },
            { label: "의존", value: "dependent" },
          ],
        },
      ],
    },
    {
      id: "section-evaluation",
      title: "평가 결과",
      order: 2,
      fields: [
        {
          id: "field-evaluator-opinion",
          type: "textarea",
          label: "평가자의견",
          name: "evaluator_opinion",
          rows: 6,
          width: "full",
        },
        {
          id: "field-recommended-device",
          type: "textarea",
          label: "추천 보조기기",
          name: "recommended_device",
          rows: 4,
          width: "full",
        },
        {
          id: "field-future-plan",
          type: "textarea",
          label: "향후 계획",
          name: "future_plan",
          rows: 4,
          width: "full",
        },
      ],
    },
  ],
}

/**
 * 모든 평가 영역 템플릿 맵
 */
export const assessmentTemplates: Record<AssessmentDomainType, FormTemplate> = {
  WC: wheelchairAssessmentTemplate,
  ADL: adlAssessmentTemplate,
  S: {
    ...wheelchairAssessmentTemplate,
    id: "assessment-s-template",
    name: "감각 평가",
    description: "감각 기능 평가 양식",
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-sensory-assessment",
        title: "감각 기능 평가",
        order: 1,
        fields: [
          {
            id: "field-vision",
            type: "select",
            label: "시각",
            name: "vision",
            width: "half",
            options: [
              { label: "정상", value: "normal" },
              { label: "경도 장애", value: "mild" },
              { label: "중도 장애", value: "moderate" },
              { label: "중증 장애", value: "severe" },
            ],
          },
          {
            id: "field-hearing",
            type: "select",
            label: "청각",
            name: "hearing",
            width: "half",
            options: [
              { label: "정상", value: "normal" },
              { label: "경도 장애", value: "mild" },
              { label: "중도 장애", value: "moderate" },
              { label: "중증 장애", value: "severe" },
            ],
          },
          {
            id: "field-tactile",
            type: "select",
            label: "촉각",
            name: "tactile",
            width: "half",
            options: [
              { label: "정상", value: "normal" },
              { label: "경도 장애", value: "mild" },
              { label: "중도 장애", value: "moderate" },
              { label: "중증 장애", value: "severe" },
            ],
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
  SP: {
    id: "assessment-sp-template",
    name: "자세 평가",
    description: "자세 및 지지 평가 양식",
    version: "1.0.0",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-posture-assessment",
        title: "자세 평가",
        order: 1,
        fields: [
          {
            id: "field-sitting-posture",
            type: "select",
            label: "앉은 자세",
            name: "sitting_posture",
            width: "half",
            options: [
              { label: "정상", value: "normal" },
              { label: "경도 이상", value: "mild" },
              { label: "중도 이상", value: "moderate" },
              { label: "중증 이상", value: "severe" },
            ],
          },
          {
            id: "field-standing-posture",
            type: "select",
            label: "선 자세",
            name: "standing_posture",
            width: "half",
            options: [
              { label: "정상", value: "normal" },
              { label: "경도 이상", value: "mild" },
              { label: "중도 이상", value: "moderate" },
              { label: "중증 이상", value: "severe" },
            ],
          },
          {
            id: "field-posture-support",
            type: "multiselect",
            label: "필요한 지지",
            name: "posture_support",
            width: "full",
            options: [
              { label: "머리 지지", value: "head_support" },
              { label: "등 지지", value: "back_support" },
              { label: "골반 지지", value: "pelvic_support" },
              { label: "다리 지지", value: "leg_support" },
              { label: "발 지지", value: "foot_support" },
            ],
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
  EC: {
    id: "assessment-ec-template",
    name: "주택 및 환경개조 평가",
    description: "주거 환경 개조 평가 양식",
    version: "1.0.0",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-environment-assessment",
        title: "환경 평가",
        order: 1,
        fields: [
          {
            id: "field-housing-type",
            type: "select",
            label: "주거 형태",
            name: "housing_type",
            width: "half",
            options: [
              { label: "단독주택", value: "house" },
              { label: "아파트", value: "apartment" },
              { label: "다가구주택", value: "multi_family" },
              { label: "시설", value: "facility" },
            ],
          },
          {
            id: "field-barriers",
            type: "multiselect",
            label: "환경 장애물",
            name: "barriers",
            width: "full",
            options: [
              { label: "계단", value: "stairs" },
              { label: "문턱", value: "threshold" },
              { label: "좁은 통로", value: "narrow_passage" },
              { label: "욕실 접근 어려움", value: "bathroom_access" },
              { label: "주방 접근 어려움", value: "kitchen_access" },
            ],
          },
          {
            id: "field-modifications-needed",
            type: "multiselect",
            label: "필요한 개조 사항",
            name: "modifications_needed",
            width: "full",
            options: [
              { label: "경사로 설치", value: "ramp" },
              { label: "엘리베이터 설치", value: "elevator" },
              { label: "욕실 개조", value: "bathroom_modification" },
              { label: "주방 개조", value: "kitchen_modification" },
              { label: "문 폭 확대", value: "door_widening" },
              { label: "손잡이 설치", value: "handrails" },
            ],
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
  CA: {
    id: "assessment-ca-template",
    name: "컴퓨터 접근 평가",
    description: "컴퓨터 및 정보통신 접근 평가 양식",
    version: "1.0.0",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-computer-assessment",
        title: "컴퓨터 접근 평가",
        order: 1,
        fields: [
          {
            id: "field-computer-experience",
            type: "select",
            label: "컴퓨터 사용 경험",
            name: "computer_experience",
            width: "half",
            options: [
              { label: "신규", value: "new" },
              { label: "초급", value: "beginner" },
              { label: "중급", value: "intermediate" },
              { label: "고급", value: "advanced" },
            ],
          },
          {
            id: "field-input-method",
            type: "multiselect",
            label: "입력 방법",
            name: "input_method",
            width: "full",
            options: [
              { label: "일반 키보드", value: "standard_keyboard" },
              { label: "대체 키보드", value: "alternative_keyboard" },
              { label: "마우스", value: "mouse" },
              { label: "트랙볼", value: "trackball" },
              { label: "스위치", value: "switch" },
              { label: "음성 인식", value: "voice_recognition" },
              { label: "눈 추적", value: "eye_tracking" },
            ],
          },
          {
            id: "field-output-method",
            type: "multiselect",
            label: "출력 방법",
            name: "output_method",
            width: "full",
            options: [
              { label: "일반 모니터", value: "standard_monitor" },
              { label: "큰 글씨 모니터", value: "large_monitor" },
              { label: "스크린 리더", value: "screen_reader" },
              { label: "음성 출력", value: "voice_output" },
              { label: "점자 디스플레이", value: "braille_display" },
            ],
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
  L: {
    id: "assessment-l-template",
    name: "레저 평가",
    description: "레저 및 여가 활동 평가 양식",
    version: "1.0.0",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-leisure-assessment",
        title: "레저 활동 평가",
        order: 1,
        fields: [
          {
            id: "field-leisure-interests",
            type: "multiselect",
            label: "관심 있는 레저 활동",
            name: "leisure_interests",
            width: "full",
            options: [
              { label: "스포츠", value: "sports" },
              { label: "음악", value: "music" },
              { label: "미술", value: "art" },
              { label: "독서", value: "reading" },
              { label: "게임", value: "games" },
              { label: "여행", value: "travel" },
              { label: "기타", value: "other" },
            ],
          },
          {
            id: "field-participation-level",
            type: "select",
            label: "참여 수준",
            name: "participation_level",
            width: "half",
            options: [
              { label: "독립", value: "independent" },
              { label: "보조 필요", value: "assist_required" },
              { label: "의존", value: "dependent" },
            ],
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
  AAC: {
    id: "assessment-aac-template",
    name: "보완대체의사소통 평가",
    description: "의사소통 보조기기 평가 양식",
    version: "1.0.0",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-communication-assessment",
        title: "의사소통 평가",
        order: 1,
        fields: [
          {
            id: "field-communication-method",
            type: "multiselect",
            label: "현재 의사소통 방법",
            name: "communication_method",
            width: "full",
            options: [
              { label: "구어", value: "verbal" },
              { label: "수화", value: "sign_language" },
              { label: "그림/사진", value: "pictures" },
              { label: "의사소통판", value: "communication_board" },
              { label: "전자 의사소통기기", value: "electronic_device" },
              { label: "기타", value: "other" },
            ],
          },
          {
            id: "field-communication-needs",
            type: "textarea",
            label: "의사소통 욕구",
            name: "communication_needs",
            rows: 4,
            width: "full",
            placeholder: "일상생활에서 필요한 의사소통 상황을 입력하세요",
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
  AM: {
    id: "assessment-am-template",
    name: "자동차 개조 평가",
    description: "자동차 개조 및 운전 보조기기 평가 양식",
    version: "1.0.0",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
    sections: [
      {
        id: "section-basic-info",
        title: "기본 정보",
        order: 0,
        fields: [
          {
            id: "field-evaluation-date",
            type: "date",
            label: "평가일",
            name: "evaluation_date",
            required: true,
            defaultValue: new Date().toISOString().split("T")[0],
            width: "half",
          },
          {
            id: "field-evaluator",
            type: "text",
            label: "평가자",
            name: "evaluator_name",
            width: "half",
          },
        ],
      },
      {
        id: "section-vehicle-assessment",
        title: "자동차 개조 평가",
        order: 1,
        fields: [
          {
            id: "field-vehicle-type",
            type: "select",
            label: "차량 유형",
            name: "vehicle_type",
            width: "half",
            options: [
              { label: "승용차", value: "passenger_car" },
              { label: "승합차", value: "van" },
              { label: "기타", value: "other" },
            ],
          },
          {
            id: "field-modifications-needed",
            type: "multiselect",
            label: "필요한 개조 사항",
            name: "modifications_needed",
            width: "full",
            options: [
              { label: "핸들 조작 장치", value: "steering_modification" },
              { label: "가속/브레이크 조작 장치", value: "pedal_modification" },
              { label: "휠체어 탑승 장치", value: "wheelchair_lift" },
              { label: "시트 개조", value: "seat_modification" },
              { label: "기타", value: "other" },
            ],
          },
        ],
      },
      {
        id: "section-evaluation",
        title: "평가 결과",
        order: 2,
        fields: [
          {
            id: "field-evaluator-opinion",
            type: "textarea",
            label: "평가자의견",
            name: "evaluator_opinion",
            rows: 6,
            width: "full",
          },
          {
            id: "field-recommended-device",
            type: "textarea",
            label: "추천 보조기기",
            name: "recommended_device",
            rows: 4,
            width: "full",
          },
          {
            id: "field-future-plan",
            type: "textarea",
            label: "향후 계획",
            name: "future_plan",
            rows: 4,
            width: "full",
          },
        ],
      },
    ],
  },
}
