import type { FormTemplate } from "@/lib/types/form-builder.types"

/**
 * 기본 상담 기록지 템플릿 (첨부 19 양식)
 * 이 템플릿은 자유롭게 수정할 수 있습니다
 */
export const defaultIntakeTemplate: FormTemplate = {
  id: "default-intake-template",
  name: "상담 기록지 (첨부 19)",
  description: "기본 상담 기록지 양식입니다. 필요에 따라 자유롭게 수정하세요.",
  version: "1.0.0",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  isDefault: true,
  sections: [
    {
      id: "section-consult-info",
      title: "상담 정보",
      description: "상담일 및 상담자 정보",
      collapsible: false,
      collapsed: false,
      order: 0,
      fields: [
        {
          id: "field-consult-date",
          type: "date",
          label: "상담일",
          name: "consult_date",
          required: true,
          defaultValue: new Date().toISOString().split("T")[0],
          width: "half",
        },
        {
          id: "field-consultant",
          type: "text",
          label: "상담자",
          name: "consultant_name",
          placeholder: "상담자 이름",
          width: "half",
        },
      ],
    },
    {
      id: "section-client-info",
      title: "대상자 정보",
      description: "대상자의 기본 정보 (자동 입력)",
      collapsible: true,
      collapsed: true,
      order: 1,
      fields: [
        {
          id: "field-name",
          type: "text",
          label: "이름",
          name: "name",
          readonly: true,
          width: "half",
        },
        {
          id: "field-birth-gender",
          type: "text",
          label: "생년월일(나이)/성별",
          name: "birth_gender",
          readonly: true,
          width: "half",
        },
        {
          id: "field-contact",
          type: "tel",
          label: "연락처 (본인)",
          name: "contact",
          readonly: true,
          width: "half",
        },
        {
          id: "field-guardian-contact",
          type: "tel",
          label: "연락처 (보호자)",
          name: "guardian_contact",
          readonly: true,
          width: "half",
        },
        {
          id: "field-address",
          type: "textarea",
          label: "주소",
          name: "address",
          readonly: true,
          rows: 2,
          width: "full",
        },
      ],
    },
    {
      id: "section-housing",
      title: "주거형태",
      description: "주거 환경 정보",
      collapsible: false,
      collapsed: false,
      order: 2,
      fields: [
        {
          id: "field-housing-type",
          type: "select",
          label: "주거형태",
          name: "housing_type",
          width: "third",
          options: [
            { label: "단독주택", value: "단독주택" },
            { label: "다가구주택", value: "다가구주택" },
            { label: "아파트", value: "아파트" },
            { label: "기타", value: "기타" },
          ],
        },
        {
          id: "field-housing-floor",
          type: "number",
          label: "층수",
          name: "housing_floor",
          placeholder: "층",
          width: "third",
        },
        {
          id: "field-has-elevator",
          type: "boolean",
          label: "엘리베이터 유",
          name: "has_elevator",
          width: "third",
        },
        {
          id: "field-obstacles",
          type: "text",
          label: "장애물",
          name: "obstacles",
          placeholder: "주거 환경의 장애물",
          width: "full",
        },
      ],
    },
    {
      id: "section-economic",
      title: "경제상황",
      description: "경제적 상황 및 연계 가능 재원",
      collapsible: false,
      collapsed: false,
      order: 3,
      fields: [
        {
          id: "field-economic-status",
          type: "select",
          label: "경제상황",
          name: "economic_status",
          width: "half",
          options: [
            { label: "기초생활수급자", value: "기초생활수급자" },
            { label: "차상위", value: "차상위" },
            { label: "건강보험", value: "건강보험" },
          ],
        },
        {
          id: "field-funding-sources",
          type: "multiselect",
          label: "연계가능재원",
          name: "funding_sources",
          width: "full",
          options: [
            { label: "보조기기교부사업", value: "보조기기교부사업" },
            { label: "보장구 건강보험", value: "보장구 건강보험" },
            { label: "보장구 의료급여", value: "보장구 의료급여" },
            { label: "노인장기요양보험", value: "노인장기요양보험" },
            { label: "정보통신보조기기", value: "정보통신보조기기" },
            { label: "고용공단 보조공학기기", value: "고용공단 보조공학기기" },
            { label: "산업재해 재활보조기기지원", value: "산업재해 재활보조기기지원" },
            { label: "보철구지급사업", value: "보철구지급사업" },
            { label: "자동차보험", value: "자동차보험" },
            { label: "민간급여", value: "민간급여" },
            { label: "바우처지원", value: "바우처지원" },
            { label: "기타", value: "기타" },
          ],
        },
      ],
    },
    {
      id: "section-disability",
      title: "장애정보",
      description: "장애 유형 및 발생 정보",
      collapsible: false,
      collapsed: false,
      order: 4,
      fields: [
        {
          id: "field-disability-type",
          type: "text",
          label: "장애유형/정도",
          name: "disability_type",
          placeholder: "장애유형 (심한/심하지 않은)",
          width: "half",
        },
        {
          id: "field-disability-cause",
          type: "text",
          label: "장애발생원인",
          name: "disability_cause",
          width: "half",
        },
        {
          id: "field-disability-onset-date",
          type: "date",
          label: "장애발생시기",
          name: "disability_onset_date",
          width: "half",
        },
      ],
    },
    {
      id: "section-body-function",
      title: "신체 기능 제한",
      description: "현재 장애 상태 - 신체 기능 제한 (관절가동범위 등)",
      collapsible: false,
      collapsed: false,
      order: 5,
      fields: [
        {
          id: "field-body-limitations",
          type: "multiselect",
          label: "신체 기능 제한 부위",
          name: "body_limitations",
          width: "full",
          options: [
            { label: "어깨관절(L)", value: "shoulder_l" },
            { label: "위팔(L)", value: "upper_arm_l" },
            { label: "팔꿉관절(L)", value: "elbow_l" },
            { label: "아래팔(L)", value: "forearm_l" },
            { label: "손목(L)", value: "wrist_l" },
            { label: "손(L)", value: "hand_l" },
            { label: "엉덩관절(L)", value: "hip_l" },
            { label: "넓적다리(L)", value: "thigh_l" },
            { label: "무릎관절(L)", value: "knee_l" },
            { label: "종아리(L)", value: "calf_l" },
            { label: "발목(L)", value: "ankle_l" },
            { label: "발(L)", value: "foot_l" },
            { label: "어깨관절(R)", value: "shoulder_r" },
            { label: "위팔(R)", value: "upper_arm_r" },
            { label: "팔꿉관절(R)", value: "elbow_r" },
            { label: "아래팔(R)", value: "forearm_r" },
            { label: "손목(R)", value: "wrist_r" },
            { label: "손(R)", value: "hand_r" },
            { label: "엉덩관절(R)", value: "hip_r" },
            { label: "넓적다리(R)", value: "thigh_r" },
            { label: "무릎관절(R)", value: "knee_r" },
            { label: "종아리(R)", value: "calf_r" },
            { label: "발목(R)", value: "ankle_r" },
            { label: "발(R)", value: "foot_r" },
            { label: "언어", value: "language" },
            { label: "인지", value: "cognitive" },
            { label: "시각", value: "vision" },
            { label: "청각", value: "hearing" },
            { label: "머리", value: "head" },
            { label: "목", value: "neck" },
            { label: "체간", value: "trunk" },
            { label: "척수", value: "spine" },
          ],
        },
      ],
    },
    {
      id: "section-cognitive-sensory",
      title: "인지/감각 기능",
      description: "인지 및 감각 기능 상태",
      collapsible: false,
      collapsed: false,
      order: 6,
      fields: [
        {
          id: "field-cognitive-sensory",
          type: "multiselect",
          label: "인지/감각 기능",
          name: "cognitive_sensory",
          width: "full",
          options: [
            { label: "인지장애", value: "인지장애" },
            { label: "시각장애", value: "시각장애" },
            { label: "청각장애", value: "청각장애" },
            { label: "언어장애", value: "언어장애" },
            { label: "기타", value: "기타" },
          ],
        },
      ],
    },
    {
      id: "section-consultation",
      title: "상담 내용 및 이용자욕구",
      description: "상세 상담 내용",
      collapsible: false,
      collapsed: false,
      order: 7,
      fields: [
        {
          id: "field-consultation-content",
          type: "textarea",
          label: "상담 내용",
          name: "consultation_content",
          description: "장애 상태 상세, 직업, 가족력, 이력 사항, 질병, 약물, 이용 서비스 등",
          placeholder: "상담 내용을 입력하세요",
          rows: 8,
          width: "full",
        },
      ],
    },
    {
      id: "section-devices",
      title: "보유 보조기기",
      description: "현재 보유하고 있는 보조기기 목록",
      collapsible: false,
      collapsed: false,
      order: 8,
      fields: [
        {
          id: "field-current-devices",
          type: "textarea",
          label: "보유 보조기기 목록",
          name: "current_devices_text",
          description: "보조기기명, 활용여부, 수급경로, 년도를 입력하세요 (예: 휠체어, 활용중, 보조기기교부사업, 2023)",
          rows: 4,
          width: "full",
        },
      ],
    },
    {
      id: "section-activity",
      title: "활동 / 환경",
      description: "주요 활동 및 환경 정보",
      collapsible: false,
      collapsed: false,
      order: 9,
      fields: [
        {
          id: "field-main-activity-place",
          type: "select",
          label: "주요 활동 장소",
          name: "main_activity_place",
          width: "half",
          options: [
            { label: "집", value: "집" },
            { label: "학교", value: "학교" },
            { label: "직장", value: "직장" },
            { label: "지역사회", value: "지역사회" },
            { label: "병원", value: "병원" },
            { label: "기타", value: "기타" },
          ],
        },
        {
          id: "field-activity-details",
          type: "text",
          label: "활동사항 (학습, 업무, ADL)",
          name: "activity_details",
          width: "half",
        },
        {
          id: "field-activity-posture",
          type: "select",
          label: "활동 시 자세",
          name: "activity_posture",
          width: "half",
          options: [
            { label: "누운자세", value: "누운자세" },
            { label: "앉은자세", value: "앉은자세" },
            { label: "선 자세", value: "선 자세" },
            { label: "기타", value: "기타" },
          ],
        },
        {
          id: "field-main-supporter",
          type: "select",
          label: "활동 주지원자",
          name: "main_supporter",
          width: "half",
          options: [
            { label: "가족", value: "가족" },
            { label: "친구", value: "친구" },
            { label: "간병인", value: "간병인" },
            { label: "활동보조인", value: "활동보조인" },
            { label: "기타", value: "기타" },
          ],
        },
        {
          id: "field-environment-limitations",
          type: "textarea",
          label: "환경 제한 사항",
          name: "environment_limitations",
          rows: 3,
          width: "full",
        },
      ],
    },
  ],
}
